# Generated by Django 6.0.4 on 2026-05-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Numero de la Cabaña')),
                ('description', models.TextField(verbose_name='Descripcion de la Cabaña')),
                ('rooms', models.IntegerField(verbose_name='Nro. de Habitaciones')),
                ('bathroom', models.IntegerField(verbose_name='Nro. de Baños')),
                ('dining_room', models.CharField(max_length=20, verbose_name='Comedor')),
                ('kitchen', models.CharField(max_length=20, verbose_name='Cocina')),
                ('availability', models.BooleanField(verbose_name='Disponibilidad de la Cabaña')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name': 'cabin',
                'verbose_name_plural': 'cabins',
            },
        ),
    ]
